### ISSUE TITLE
qdarkstyle的加载导致 显示不出”学号密码确定密码“

### ISSUE THREAD

**Issue by Leo-Lionni** [ycdxsb/LibraryManageDesktopApp#2]
在signUP.py中，如果不加载 app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())，则会正常显示出  注册界面的 ”学号，密码，确认密码，“，如果加载，则会导致”学号，密码，确认密码“消失。。
相反地，在signIN.py中，qdarkstyle并没有导致”账号密码“消失。

请问一下，问题出在哪里呢？是因为布局吗？

**Comment by Leo-Lionni** [comment]
![image](https://user-images.githubusercontent.com/35078844/64484450-d7b3ba80-d244-11e9-8ccf-8d4f558ff422.png)

**Comment by Leo-Lionni** [comment]
![image](https://user-images.githubusercontent.com/35078844/64484480-3416da00-d245-11e9-93dd-4820af96f5ca.png)

**Comment by ycdxsb** [comment]
可以对着https://github.com/ycdxsb/LibraryManageDesktopApp/tree/master/venv/Lib/site-packages中的包看下是否是版本问题
